<a href="https://colab.research.google.com/github/pavankumarallu/Pytorch-Practice/blob/main/Pythorch_Basics_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
#create an empty tensor
x = torch.empty(3,2,2,3)
print(x)

tensor([[[[ 5.0466e-35,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  1.4013e-45,  0.0000e+00]],

         [[ 5.2085e-38,  0.0000e+00,  7.5225e-35],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[ 7.6310e-35,  0.0000e+00,  4.1801e-36],
          [ 0.0000e+00, -9.0845e-18,  4.5667e-41]],

         [[ 2.8026e-45,  0.0000e+00,  2.8026e-45],
          [ 0.0000e+00,  4.2039e-45,  0.0000e+00]]],


        [[[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 4.2039e-45,  0.0000e+00,  1.4013e-45],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]]])


In [ ]:
#create random values
x = torch.rand(2,2)
x

tensor([[0.2392, 0.3538],
        [0.5269, 0.8504]])

In [ ]:
#zeroes and ones
x0 = torch.zeros(2,2)
x1 = torch.ones(2,2)
x0,x1

(tensor([[0., 0.],
         [0., 0.]]), tensor([[1., 1.],
         [1., 1.]]))

In [ ]:
x = torch.tensor([2.5,0.1])
x

tensor([2.5000, 0.1000])

In [ ]:
#operations on tensors
x = torch.rand(2,2)
y = torch.rand(2,2)
z = torch.add(x,y)
aa = torch.sub(x,y)
ab = torch.mul(x,y)
ac = torch.div(x,y)
z,aa,ab,ac

(tensor([[0.7897, 1.6286],
         [1.2915, 0.6763]]), tensor([[ 0.7754, -0.2915],
         [-0.1874, -0.5495]]), tensor([[0.0056, 0.6418],
         [0.4082, 0.0389]]), tensor([[1.0942e+02, 6.9636e-01],
         [7.4656e-01, 1.0348e-01]]))

In [ ]:
#tensor slicing
x = torch.rand(5,3)
print(x)
print(x[0,0])

tensor([[0.2400, 0.5637, 0.8100],
        [0.8852, 0.0768, 0.3928],
        [0.9256, 0.7459, 0.9455],
        [0.4503, 0.1432, 0.2723],
        [0.3187, 0.0447, 0.5611]])
tensor(0.2400)


In [ ]:
#reshaping a tensor
x = torch.rand(4,4)
print(x)
y = x.view(-1,2)
print(y)

tensor([[0.4257, 0.7602, 0.6407, 0.0302],
        [0.7093, 0.2287, 0.3653, 0.6125],
        [0.2204, 0.4665, 0.8589, 0.4242],
        [0.8684, 0.3051, 0.3203, 0.6372]])
tensor([[0.4257, 0.7602],
        [0.6407, 0.0302],
        [0.7093, 0.2287],
        [0.3653, 0.6125],
        [0.2204, 0.4665],
        [0.8589, 0.4242],
        [0.8684, 0.3051],
        [0.3203, 0.6372]])


In [ ]:
#numpy array to tensor
import numpy as np

a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
# calculates gradients in future
x = torch.ones(2,requires_grad=True)
print(x)

tensor([1., 1.], requires_grad=True)
