<a href="https://colab.research.google.com/github/pavankumarallu/Pytorch-Practice/blob/main/Pytorch_Basics_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd package - Pytorch
* Calculate gradients using Autograd package pytorch

In [2]:
import torch

In [41]:
x = torch.rand(3, requires_grad = True)
print(x)

tensor([0.1936, 0.6933, 0.5776], requires_grad=True)


In [45]:
#if output is a sclar quantitu
y = x + 2
print(y)

y = y**2
y = y.mean()
print(y)

y.backward(retain_graph=True)
print(x.grad)

tensor([2.1936, 2.6933, 2.5776], grad_fn=<AddBackward0>)
tensor(6.2365, grad_fn=<MeanBackward0>)
tensor([2.9248, 3.5910, 3.4368])


In [52]:
#if output is not a scalar
y = x + 2
y = y**2
v  =torch.tensor([0.1,0.1,0.001],dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([4.2409, 5.2070, 3.4523])


In [58]:
#training example

weights = torch.rand(4 , requires_grad=True)
print(weights)
for epoch in range(12):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)

tensor([0.2886, 0.9366, 0.4006, 0.7748], requires_grad=True)
tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])
tensor([12., 12., 12., 12.])
tensor([15., 15., 15., 15.])
tensor([18., 18., 18., 18.])
tensor([21., 21., 21., 21.])
tensor([24., 24., 24., 24.])
tensor([27., 27., 27., 27.])
tensor([30., 30., 30., 30.])
tensor([33., 33., 33., 33.])
tensor([36., 36., 36., 36.])
